services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=its
      - POSTGRES_PASSWORD=testpw
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080