services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=testpw
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
