version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: its_admin
      MYSQL_PASSWORD: test123
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: its-mysql
    ports:
      - 3306:3306
  kv:
    image: redis
    ports:
      - 6379:6379
  vector:
    image: qdrant/qdrant
    ports:
      - 6333:6333
